/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlGUIPrincipal;
import java.awt.event.ActionListener;

/**
 *
 * @author Né
 */
public class GUIPrincipal extends javax.swing.JFrame {

    private ControlGUIPrincipal control;

    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        control=new ControlGUIPrincipal();
        this.escuchar(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnVenta = new javax.swing.JButton();
        btnInventario = new javax.swing.JButton();
        btnCompra = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnArchivo = new javax.swing.JMenu();
        mniSalir = new javax.swing.JMenuItem();
        mnModulos = new javax.swing.JMenu();
        mniCompra = new javax.swing.JMenuItem();
        mniVenta = new javax.swing.JMenuItem();
        mniInventario = new javax.swing.JMenuItem();
        mniProveedores = new javax.swing.JMenuItem();
        mniProductos = new javax.swing.JMenuItem();
        mniReporte = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GUIPrincipal.png"))); // NOI18N

        btnVenta.setText("Venta");
        btnVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentaActionPerformed(evt);
            }
        });

        btnInventario.setText("Inventario");

        btnCompra.setText("Compra");
        btnCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVenta, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInventario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCompra, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnCompra)
                        .addGap(18, 18, 18)
                        .addComponent(btnVenta)
                        .addGap(18, 18, 18)
                        .addComponent(btnInventario))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        mnArchivo.setText("Archivo");

        mniSalir.setText("Salir");
        mniSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniSalirActionPerformed(evt);
            }
        });
        mnArchivo.add(mniSalir);

        jMenuBar1.add(mnArchivo);

        mnModulos.setText("Modulos");

        mniCompra.setText("Compra");
        mnModulos.add(mniCompra);

        mniVenta.setText("Venta");
        mniVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniVentaActionPerformed(evt);
            }
        });
        mnModulos.add(mniVenta);

        mniInventario.setText("Inventario");
        mnModulos.add(mniInventario);

        mniProveedores.setText("Reg. Proveedores");
        mniProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProveedoresActionPerformed(evt);
            }
        });
        mnModulos.add(mniProveedores);

        mniProductos.setText("Reg. Productos");
        mniProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniProductosActionPerformed(evt);
            }
        });
        mnModulos.add(mniProductos);

        mniReporte.setText("Reporte");
        mnModulos.add(mniReporte);

        jMenuBar1.add(mnModulos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniProductosActionPerformed

    private void mniProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniProveedoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniProveedoresActionPerformed

    private void mniVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniVentaActionPerformed

    private void mniSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mniSalirActionPerformed

    private void btnVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVentaActionPerformed

    private void btnCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompra;
    private javax.swing.JButton btnInventario;
    private javax.swing.JButton btnVenta;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu mnArchivo;
    private javax.swing.JMenu mnModulos;
    private javax.swing.JMenuItem mniCompra;
    private javax.swing.JMenuItem mniInventario;
    private javax.swing.JMenuItem mniProductos;
    private javax.swing.JMenuItem mniProveedores;
    private javax.swing.JMenuItem mniReporte;
    private javax.swing.JMenuItem mniSalir;
    private javax.swing.JMenuItem mniVenta;
    // End of variables declaration//GEN-END:variables

    public static final String BTN_COMPRA="Compra", 
            BTN_VENTA="Venta", 
            BTN_INVENTARIO="Inventario",
            MNI_SALIR="Salir",
            MNI_COMPRA="Compra",
            MNI_VENTA="Venta",
            MNI_INVENTARIO="Inventario",
            MNI_REG_PROVEEDORES="Reg. Proveedores",
            MNI_REG_PRODUCTO="Reg. Productos",
            MNI_REPORTE="Reporte";
    
    public void escuchar(ActionListener control){
        this.btnCompra.addActionListener(control);
        this.btnVenta.addActionListener(control);
        this.btnInventario.addActionListener(control);
        this.mniCompra.addActionListener(control);
        this.mniVenta.addActionListener(control);
        this.mniInventario.addActionListener(control);
        this.mniProveedores.addActionListener(control);
        this.mniProductos.addActionListener(control);
        this.mniReporte.addActionListener(control);
        this.mniSalir.addActionListener(control);
    }
    
    
}
