/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlRegProductos;
import java.awt.event.ActionListener;

/**
 *
 * @author Raul
 */
public class RegistroProductos extends javax.swing.JFrame {

    /**
     * Creates new form RegistroProductos
     */
    public RegistroProductos() {
        initComponents();
        ControlRegProductos control = new ControlRegProductos();
        this.escuchar(control);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProcesadores = new javax.swing.JButton();
        btnComputadores = new javax.swing.JButton();
        btnOtros = new javax.swing.JButton();
        btnMemorias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnProcesadores.setText("Procesadores");
        btnProcesadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcesadoresActionPerformed(evt);
            }
        });

        btnComputadores.setText("Computadores");

        btnOtros.setText("Otros");
        btnOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtrosActionPerformed(evt);
            }
        });

        btnMemorias.setText("Memorias");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnMemorias)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOtros)
                            .addComponent(btnComputadores)
                            .addComponent(btnProcesadores))
                        .addGap(40, 150, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnProcesadores)
                .addGap(18, 18, 18)
                .addComponent(btnMemorias)
                .addGap(18, 18, 18)
                .addComponent(btnComputadores)
                .addGap(18, 18, 18)
                .addComponent(btnOtros)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcesadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProcesadoresActionPerformed

    private void btnOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOtrosActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComputadores;
    private javax.swing.JButton btnMemorias;
    private javax.swing.JButton btnOtros;
    private javax.swing.JButton btnProcesadores;
    // End of variables declaration//GEN-END:variables

    public static final String BTN_PROCESADORES="Procesadores";
    public static final String BTN_MEMORIAS="Memorias";
    public static final String BTN_COMPUTADORES="Computadores";
    public static final String BTN_OTROS="Otros";
    
    public void escuchar(ActionListener control){
        this.btnProcesadores.addActionListener(control);
        this.btnMemorias.addActionListener(control);
        this.btnComputadores.addActionListener(control);
        this.btnOtros.addActionListener(control);
    }
    
}
